cookie:
  expiry_days: 0
  key: key
  name: hola
credentials:
  usernames:
    affectedDingo2:
      name: affectedDingo2
      password: $2b$12$lRXnQffNlRFyUCSJ9EeGdObvYoYMJAC1Xg5F/JSWHJKRz.EhtNJIG
    ashamedSnail4:
      name: ashamedSnail4
      password: $2b$12$qKFRyNdL6QO6xlkBrCM0IOqXl..bgNAjkyqLhbnWYKOhsFe3HnozW
    awedWildfowl5:
      name: awedWildfowl5
      password: $2b$12$K9buPnF4X/rfim7R4P.WGOJkd/WhPOdVzC57LRdR/QGNM40NSAe7e
    boastfulSalt0:
      name: boastfulSalt0
      password: $2b$12$S3TZL6UZhi3.9K9fA6ijk.iChguk3WKAnaQbIf72cIPbTuzJhukMq
    cruelMare1:
      name: cruelMare1
      password: $2b$12$suhvd5iN4FHSCWIcwgCL4utyo2g.6cgGp5TVO9dZHK9G//bdpKJBS
    debonairOatmeal3:
      name: debonairOatmeal3
      password: $2b$12$NmhirlRcTYA59wrSF3XjW.L6lhVouy3Cy4Zg9xOEJWDNppPSdSfYW
    dopeyDunbird4:
      name: dopeyDunbird4
      password: $2b$12$ffjllMBzOF1Do09wKWeJ/uCuEK79WYGv.BYNvBJitGr1wjPsJPFMq
    empathicChamois3:
      name: empathicChamois3
      password: $2b$12$IqT6pGP5NrsTKtD4rKKhneB6diHM/cGf0Wd1ZXYWz2AjVrQKBGJB.
    enragedPup6:
      name: enragedPup6
      password: $2b$12$X7n67QrFbJEinU72DP6GZ.W6.7Ba89vRcxCRiXtDwL50DER9kntBa
    enragedTermite8:
      name: enragedTermite8
      password: $2b$12$uYlZ.l3jMQPr3PeFVYQDe.2UQZ.cYTCFdeYLKIttzCqLfAXAfd15u
    goofyLocust4:
      name: goofyLocust4
      password: $2b$12$aW4pOE/TRAu8cn9NDowLYed0PytdbTP5UnQIhWl5Ari2DdJR192k2
    holisticViper1:
      name: holisticViper1
      password: $2b$12$r81Yv8E4OkMKl8PcYxHoyuQ7dWV./mtnutm8ADuJro9Smt3gF30a2
    lyingCheese2:
      name: lyingCheese2
      password: $2b$12$J9s6NBPuVJsGyvmBjZuC/u6iT3pmJxdZ7r82ps58EbiJUsJohD4UK
    lyingSmelt5:
      name: lyingSmelt5
      password: $2b$12$A4.BWyboAH/1Fx4mOKxFFO7FzZjhWQaaYVqbQZJVpWOWjCSJUP.tK
    madBuck9:
      name: madBuck9
      password: $2b$12$YPav3/uu.CNK0acOzobWqO0sa5EdEfkpTiAEZxVQD/uKQxSqD5hTO
    morbidChowder8:
      name: morbidChowder8
      password: $2b$12$avvos.hzYq7hJHZvJ9c9kukeh6uhlC8w.oJUz3bICwVO6YO/ctT..
    needfulLeopard6:
      name: needfulLeopard6
      password: $2b$12$J23IVQG9UQ.cGDrpR2xOhOf7/uzmnyw2AfOM4vrY1U199CvlHglJW
    needfulMallard7:
      name: needfulMallard7
      password: $2b$12$9vWGC6cWgJwNqHXwFSFnnulPKkxMN0.0sDr1.8maxLZb99RCFdOgq
    offendedMandrill6:
      name: offendedMandrill6
      password: $2b$12$cs7Y/xj1l7Qt9czzSvDNduwFXQt9YPHh7FycnubK70cBAEKurUndO
    pleasedRelish8:
      name: pleasedRelish8
      password: $2b$12$mKCMUel4o8id6yLY.iG1bOc2geuNjzdZn6lHIbPhMkOfvebUbyGnG
    pluckyIcecream4:
      name: pluckyIcecream4
      password: $2b$12$lPUMymq2bPPm6dJ3MnmnPObJMUvMAEOuiV.xX8JOALmagCIsph0Ly
    resolvedMeerkat7:
      name: resolvedMeerkat7
      password: $2b$12$svkKLv3vrunWp9oeZKglfOqRoZKFXOZNocjhkU5DkkSHs598JohWm
    solidLemur4:
      name: solidLemur4
      password: $2b$12$G9aNsOeIn9Y10fSfReCuiOC9ICfxofKD8vkb4zGbEsXp2KZx.JE3W
    solidMagpie9:
      name: solidMagpie9
      password: $2b$12$oN.W92TeUa4lPTk343sDp.4v06UXStbOR8oGbAacwvEkOiByabozy
    spiritedSmelt7:
      name: spiritedSmelt7
      password: $2b$12$glSkjyhOEQES7cOI4xvHYuQdTlbDGxGEsCaD0QvLU7Z.WMgZB29gO
    trustingMallard9:
      name: trustingMallard9
      password: $2b$12$WnEvrs/LnuumBI5l47m0seSDPdAUQZDxezvxeakLxWduOgqOaH2Eq
    wingedMandrill6:
      name: wingedMandrill6
      password: $2b$12$GZjvTQsj74ywkAb5mZBGFuYUD2eQBHRKIeoMjLkmAUZouTfdTMXFa
    zestyAbalone5:
      name: zestyAbalone5
      password: $2b$12$t6nTId2p8dXV8ho4BJUW5uSTb9qqvxKoti.Oymf8bWcGNNCUZZcbe
    zestyIguana0:
      name: zestyIguana0
      password: $2b$12$Ul3BlOuxDN8wuTShZ5geEup2z61cBmJgD9lgUc426BQ4IVx2bBEa2
    zestyLemur6:
      name: zestyLemur6
      password: $2b$12$5wahc6OUXQ0q4tavdGsHj..ICvnlOpa2yddlagpIECocI9MLUyTpW
preauthorized:
  usernames:
  - debonairOatmeal3
  - resolvedMeerkat7
  - lyingCheese2
  - needfulLeopard6
  - morbidChowder8
  - trustingMallard9
  - ashamedSnail4
  - spiritedSmelt7
  - boastfulSalt0
  - awedWildfowl5
  - pleasedRelish8
  - holisticViper1
  - enragedPup6
  - wingedMandrill6
  - lyingSmelt5
  - goofyLocust4
  - solidMagpie9
  - solidLemur4
  - zestyAbalone5
  - zestyIguana0
  - zestyLemur6
  - cruelMare1
  - affectedDingo2
  - dopeyDunbird4
  - offendedMandrill6
  - madBuck9
  - pluckyIcecream4
  - enragedTermite8
  - empathicChamois3
  - needfulMallard7
