cookie:
  expiry_days: 0
  key: key
  name: hola
credentials:
  usernames:
    affectedDingo2:
      name: affectedDingo2
      password: $2b$12$IBgSItIVTZkogCagLLJJceLgDkmkekm3pt1.6t6KpCVdruAEHLn9O
    ashamedSnail4:
      name: ashamedSnail4
      password: $2b$12$g.As4iWUafFx2rNxMPbr7O8nIyYBUqeOGOrxaXpikb60JX1LiUYW.
    awedWildfowl5:
      name: awedWildfowl5
      password: $2b$12$A0ocaHHRasai5jBeSBd4c.2jxkrYUdkxdre3SUxnPlIeeIVqkjuny
    boastfulSalt0:
      name: boastfulSalt0
      password: $2b$12$Q.vgyYEGhz5bP8JBdPbUveeGAGnFDf7dd/i1ClVJLqjpi4UnhgqR6
    cruelMare1:
      name: cruelMare1
      password: $2b$12$eqIfVlkNgpahlo5R6ZuMyuha.T.2MBLC.YdltY90DRFv7D2c3I0OO
    debonairOatmeal3:
      name: debonairOatmeal3
      password: $2b$12$AlFXezOOnmYdV6QUekvylOcg7ylCtbjs1IRRVUvkqcxiG2XlbF7VK
    dopeyDunbird4:
      name: dopeyDunbird4
      password: $2b$12$qbg.UrrITVTqNVpO9fVEXu6lneQwGS9BYk0U.MdmSNGYQNHF6o8Vi
    empathicChamois3:
      name: empathicChamois3
      password: $2b$12$rPfjudsLQphrManWiodWiu8pCvFqxr5qk78OAirPIAQW4NeC9Mmji
    enragedPup6:
      name: enragedPup6
      password: $2b$12$mJa5.1hJhxCgBwnUOJns3Oec3zvVvoA9aUR4IiyHhtCDE2Rz99F7y
    enragedTermite8:
      name: enragedTermite8
      password: $2b$12$kyWB5D2fu2GX4sDAez5mzuWfdtIVSXnGR6Gp5sVxnezbUIHU4Bn..
    goofyLocust4:
      name: goofyLocust4
      password: $2b$12$6RPvGytZnhsYLwlHe9EYIe1mVnJBf/8kQnIx3uLpuTKQ9dfJxOac6
    holisticViper1:
      name: holisticViper1
      password: $2b$12$21GV0mW0IWwXxKpL5LMeCu45nqfc6Ci/iyZlSJ8CpRZQ/szNehZka
    lyingCheese2:
      name: lyingCheese2
      password: $2b$12$BPtBpHPDe92YmQDB0r2peehIJW.sOwOgcz5j0As6.ayT.BDqmVqX6
    lyingSmelt5:
      name: lyingSmelt5
      password: $2b$12$guf0r2p2P7AzaRVNVmLK5uNH6d4lBRlhcR1/cCKlD875asR3pqGDa
    madBuck9:
      name: madBuck9
      password: $2b$12$w.MFuYepyd8iRZvs1vkYt.LnixRQF93h3VvYh65uI2oEMsKzsu3pG
    morbidChowder8:
      name: morbidChowder8
      password: $2b$12$bGWg2PZC9mHKv1GjZCXZOOvxaaDeYW6UfJX7HMGqyuPi0yLGtqJx6
    needfulLeopard6:
      name: needfulLeopard6
      password: $2b$12$LWbxJ7B.4wwkI3lgkojytuJxgksQgjVyfMfrD9uXdEH1Cwr8/yuPa
    needfulMallard7:
      name: needfulMallard7
      password: $2b$12$KbR23hzL4bFFEKPBEKQ6teIzXKT7KcDMMZRZXj4KeF7BrQswf5LkG
    offendedMandrill6:
      name: offendedMandrill6
      password: $2b$12$bxIMJEvZGI2h2uT2DVZIFujPQId9dOL7gmO5RGoSMWeUfa/EU69la
    pleasedRelish8:
      name: pleasedRelish8
      password: $2b$12$Jyb9ht8eCMCyzFLCLfx7hOdR1WZJDZ1YCmXGxK3GeefehnGwTx6xG
    pluckyIcecream4:
      name: pluckyIcecream4
      password: $2b$12$CQsf2CWzkMtsbignSMWcku2b.kmPDqwLzUVXd/j6leouNpqmn1Ga2
    resolvedMeerkat7:
      name: resolvedMeerkat7
      password: $2b$12$phD5QnoDU2bj/4l3WHQNoe3Ig6N5LYAslLP1r/ASmmAOd.ZxvEAx6
    solidLemur4:
      name: solidLemur4
      password: $2b$12$h1SSgpNSu1sKhop4ySCWNeJn7bZIzRUP4VLGpUWMJBiItS1EfUIN6
    solidMagpie9:
      name: solidMagpie9
      password: $2b$12$zmwH9e6o56GqhqUXuQdtKOmFhb5uhk0EVKS6Xt4bUMRRUBtz9ViNe
    spiritedSmelt7:
      name: spiritedSmelt7
      password: $2b$12$77dPFKF6.kVkv85c3IoBCuRWPro6dw51g5sUVwE732fozqfVWyM9u
    trustingMallard9:
      name: trustingMallard9
      password: $2b$12$Us3nF7FslLSqdDpu3iL3RO4xz50mgRXdHsxJIOTHcsLIbln.oL0jW
    wingedMandrill6:
      name: wingedMandrill6
      password: $2b$12$PFGnvVl05sw56/AApswPgOZfrYfq5yC00dxanQwiFpsMljYdT28sC
    zestyAbalone5:
      name: zestyAbalone5
      password: $2b$12$NveWf7OkmH/IHDuJys2SJ.3cbhVMma1AVg7zodiD1eK9dEULJwe0m
    zestyIguana0:
      name: zestyIguana0
      password: $2b$12$YfZia2xCoi0SEde57XhRpuiucNaPBLGeScfiYt0rReJw385kSYjWq
    zestyLemur6:
      name: zestyLemur6
      password: $2b$12$ulWvwdQ0mAVaL3UDI35CwuT6I7HFGm/0jGhzpz3LZ3lhBjQM4r1N6
preauthorized:
  usernames:
  - debonairOatmeal3
  - resolvedMeerkat7
  - lyingCheese2
  - needfulLeopard6
  - morbidChowder8
  - trustingMallard9
  - ashamedSnail4
  - spiritedSmelt7
  - boastfulSalt0
  - awedWildfowl5
  - pleasedRelish8
  - holisticViper1
  - enragedPup6
  - wingedMandrill6
  - lyingSmelt5
  - goofyLocust4
  - solidMagpie9
  - solidLemur4
  - zestyAbalone5
  - zestyIguana0
  - zestyLemur6
  - cruelMare1
  - affectedDingo2
  - dopeyDunbird4
  - offendedMandrill6
  - madBuck9
  - pluckyIcecream4
  - enragedTermite8
  - empathicChamois3
  - needfulMallard7
